export const TEAM = [
  {
    src: "/team/img-1.jpg",
    bg: "#0B0F14",
    name: "Mohamed Hamed",
    role: "FULL-STACK DEVELOPER",
    desc: "Builds scalable web applications with React, Node.js, and Supabase. Passionate about crafting modern interfaces and delivering seamless user experiences.",
    linkedin: "https://www.linkedin.com/in/mohamed-hamed-alkafory/",
    email: "alkmohamed40@gmail.com",
    github: "https://github.com/Mohamed-Alkafory",
  },
  {
    src: "/team/img-2.jpg",
    bg: "#0B0F14",
    name: "Esraa Shalaby",
    role: "Frontend Developer",
    desc: "Passionate about creating clean, responsive, and user-friendly interfaces. Focused on delivering seamless user experiences through modern frontend technologies.",
    linkedin: "https://www.linkedin.com/in/esraa-mohamed-shalaby/?locale=ar",
    email: "esraashalaby686@gmail.com",
    github: "https://github.com/Esraa-Shalaby",
  },
  {
    src: "/team/img-3.jpeg",
    bg: "#0B0F14",
    name: "	Haneen Walid",
    role: "Frontend Developer",
    desc: "Dedicated to building intuitive and visually engaging web applications with attention to performance, accessibility, and responsive design.",
    linkedin: "https://www.linkedin.com/in/haneen-waleed-abedlwahed/",
    email: "hnyntym9@gmail.com",
    github: "https://github.com/HaneenWaleed",
  },
  {
    src: "/team/img-4.jpg",
    bg: "#0B0F14",
    name: "Huda Elmorsi",
    role: "Frontend Developer",
    desc: "Frontend developer passionate about transforming ideas into elegant digital experiences using modern UI practices and clean, maintainable code.",
    linkedin: "https://www.linkedin.com/in/huda-morsy",
    email: "hodamhmedmorsy888@gmail.com",
    github: "https://github.com/hodamhmedmorsy888-source",
  },
  {
    src: "/team/img-6.jpeg",
    bg: "#0B0F14",
    name: "Shehab Hany",
    role: "Frontend Developer",
    desc: "Rapidly learning modern frontend stack. Contributes to component testing, Storybook documentation, and cross-browser compatibility at Homi.",
    linkedin: "https://www.linkedin.com/in/shehab-hany",
    email: "shehabhany4@outlook.com",
    github: "https://github.com/shehabhany4",
  },
];
